travis:
  secure:
    BINSTAR_TOKEN: gmJtkVKAwaO0BLMm4YRqYdYFoby17NTThnbdJ9HA6vjVEUwVnUb4r764mi4UTakMavEnUOlImXwltgMhyFltdlPHuy+S6YZjdxlLqtwOLhxPaVjGrQD6hd+DGw4LYKo/p0UprKErlOPnr4s12GcsIihHHClFJgljmDBNVAe8G4TvvQchtdal9/8TOqB9WQr2YrDOxDifW78X3/k89qO9tF29fC2BbAfn2Jql2FA6qnGdBLQC+Uh9XjKk+VxO9Vm/RtaSZFSJGmmZXGsBVfiNm8NpiXtmVu75deiv6Rw3rHclxDHp8K5RNhAYhyEvDtzXu7NmnCKWNFX34qam4yUSA98HDIYSeQVdFxpTCsFVwkn6hsD3nyPClHY+PiY9wbRxtm7kSXp+Rlz9hWJuMAuesrKYAc+pFmXc4ptoNw1ATOAIEp16jmZ6HQNbNkmAalxiSOpHupRUdqqWWzGFXEengvXxidvvJKftQ1hWpVcmIcXWoD8f7227tlZE4RjKRbn45aPtXYfRzxM0vTSwmzlAI6rW8SsSvlmwD8DjgTiFHIh1B/H1AHlYSpYXFz7jIzrZaRge2QY79YIGE8+LJGCGJcaSvcoX4MI9StjRaZiEgfSTFnCVhBG9o5pWvC+DOtw7/aQepRiFeeTaiJRTPa/5uoo3DbMQliMTcwucLItLCdk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
